on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:
  push:
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync (branches)
        uses: wei/git-sync@v3
        with:
          source_repo: "https://gitlab.nic.cz/labs/bird.git"
          source_branch: "refs/remotes/source/*"
          destination_repo: "X4BNet/bird"
          destination_branch: "refs/heads/*"
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }}
      - name: git-sync (tags)
        uses: wei/git-sync@v3
        with:
          source_repo: "https://gitlab.nic.cz/labs/bird.git"
          destination_repo: "X4BNet/bird"
          source_branch: "refs/tags/*"
          destination_branch: "refs/tags/*"
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: "X4BNet/bird"
          path: bird
          fetch-depth: 0
      - name: prepare to build
        run: |
         sudo apt-get install -y python3-pip python3-setuptools
         sudo pip3 install apkg
      - name: do build
        run: |
          cd "$GITHUB_WORKSPACE/bird"
          tag=$(git tag -l --sort -version:refname | grep '^v' | head -n 1)
          echo "tagged: $tag"

          # git checkout $tag
          apt-get install debhelper docbook-xsl libssh-gcrypt-dev linuxdoc-tools-latex opensp quilt texlive-latex-extra xsltproc
          apkg build